
name: Build LaTeX Business Card

on:
  push:
    tags:
      - '*'  # déclenche sur chaque nouveau tag

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v4
        with:
          root_file: card.tex

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: card.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
